package exh.eh

/**
 * Common NHentai tags organized by namespace, used for autocomplete suggestions.
 * Tags are formatted as "namespace:tag name" for direct use in search queries.
 */
object NHTags {
    fun getNamespaces(): List<String> = listOf(
        "tag",
        "artist",
        "group",
        "parody",
        "character",
        "language",
        "category",
    )

    fun getAllTags(): List<String> = listOf(
        getCommonTags(),
        getLanguageTags(),
        getCategoryTags(),
    ).flatten()

    private fun getCommonTags(): List<String> = listOf(
        // Popular content tags
        "tag:big breasts",
        "tag:sole female",
        "tag:sole male",
        "tag:anal",
        "tag:stockings",
        "tag:glasses",
        "tag:full color",
        "tag:mosaic censorship",
        "tag:nakadashi",
        "tag:blowjob",
        "tag:lolicon",
        "tag:group",
        "tag:rape",
        "tag:ahegao",
        "tag:bondage",
        "tag:futanari",
        "tag:schoolgirl uniform",
        "tag:shotacon",
        "tag:yaoi",
        "tag:yuri",
        "tag:milf",
        "tag:defloration",
        "tag:incest",
        "tag:tentacles",
        "tag:uncensored",
        "tag:paizuri",
        "tag:femdom",
        "tag:dark skin",
        "tag:monster",
        "tag:netorare",
        "tag:harem",
        "tag:cheating",
        "tag:impregnation",
        "tag:swimsuit",
        "tag:maid",
        "tag:nurse",
        "tag:kemonomimi",
        "tag:catgirl",
        "tag:elf",
        "tag:vampire",
        "tag:demon girl",
        "tag:angel",
        "tag:witch",
        "tag:gyaru",
        "tag:tomboy",
        "tag:twintails",
        "tag:ponytail",
        "tag:short hair",
        "tag:long hair",
        "tag:collar",
        "tag:leash",
        "tag:lingerie",
        "tag:pantyhose",
        "tag:thigh high boots",
        "tag:bikini",
        "tag:apron",
        "tag:cosplaying",
        "tag:crossdressing",
        "tag:gender bender",
        "tag:mind control",
        "tag:mind break",
        "tag:double penetration",
        "tag:tribadism",
        "tag:fingering",
        "tag:handjob",
        "tag:footjob",
        "tag:x-ray",
        "tag:cum inflation",
        "tag:eye-covering bang",
        "tag:body writing",
        "tag:exhibitionism",
        "tag:voyeurism",
        "tag:public use",
        "tag:pregnant",
        "tag:lactation",
        "tag:collar",
        "tag:fox girl",
        "tag:bunny girl",
        "tag:dog girl",
        "tag:oni",
        "tag:succubus",
        "tag:slime",
        "tag:robot",
        "tag:alien",
        "tag:childhood friend",
        "tag:teacher",
        "tag:sister",
        "tag:mother",
        "tag:daughter",
        "tag:tsundere",
        "tag:yandere",
        "tag:kuudere",
        "tag:muscle",
        "tag:small breasts",
        "tag:flat chest",
        "tag:huge breasts",
        "tag:oppai loli",
        "tag:tall girl",
        "tag:short girl",
        "tag:giantess",
        "tag:bbw",
        "tag:dilf",
        "tag:males only",
        "tag:females only",
        "tag:drugs",
        "tag:sleeping",
        "tag:drunk",
        "tag:torture",
        "tag:snuff",
        "tag:guro",
        "tag:vore",
        "tag:transformation",
        "tag:body swap",
        "tag:age progression",
        "tag:age regression",
        "tag:time stop",
        "tag:invisible",
        "tag:ghost",
        "tag:zombie",
        "tag:anthology",
        "tag:artbook",
        "tag:multi-work series",
        "tag:story arc",
        "tag:tankoubon",
        "tag:webtoon",
        "tag:novel",
        "tag:non-h imageset",
    )

    private fun getLanguageTags(): List<String> = listOf(
        "language:english",
        "language:japanese",
        "language:chinese",
        "language:translated",
        "language:korean",
        "language:spanish",
        "language:french",
        "language:german",
        "language:russian",
        "language:portuguese",
        "language:italian",
        "language:thai",
        "language:vietnamese",
        "language:polish",
        "language:arabic",
        "language:indonesian",
    )

    private fun getCategoryTags(): List<String> = listOf(
        "category:doujinshi",
        "category:manga",
        "category:artist cg",
        "category:game cg",
        "category:western",
        "category:non-h",
        "category:image set",
        "category:cosplay",
        "category:asian porn",
        "category:misc",
    )
}
